working...

diff --git a/.github/workflows/build-ubuntu.yml b/.github/workflows/build-ubuntu.yml
--- a/.github/workflows/build-ubuntu.yml
+++ b/.github/workflows/build-ubuntu.yml
@@ -2,26 +2,7 @@ name: build-ubuntu
 on: [push]
 jobs:
 
-  example:
-    runs-on: ubuntu-latest
-    steps:
-    
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v1
-        
-      - name: Set up Docker Buildx
-        id: buildx
-        uses: docker/setup-buildx-action@v1
-        
-      - name: Available platforms
-        run: echo ${{ steps.buildx.outputs.platforms }}
-    
-      - name: Test
-        run: |
-            docker run -it --rm multiarch/ubuntu-core:arm64-wily 'bash -c "uname -a"'
-
-
-  Build:
+  build-job:
     runs-on: 'ubuntu-latest'
     strategy:
       fail-fast: false  
@@ -30,8 +11,9 @@ jobs:
         specs: [
             {key: 'cpyth-ngui-amd64',  platform: 'linux/amd64' , conda: '0', gui: '0', docker-image: 'visus/portable-linux-binaries_x86_64:2.0', qt5-dir: ''                      , wheel-platform-name: 'manylinux2010_x86_64'  },
             {key: 'cpyth-ygui-amd64',  platform: 'linux/amd64' , conda: '0', gui: '1', docker-image: 'visus/portable-linux-binaries_x86_64:2.0', qt5-dir: '/opt/qt512'            , wheel-platform-name: 'manylinux2010_x86_64'  },
-            {key: 'conda-ygui-amd64',  platform: 'linux/amd64' , conda: '1', gui: '1', docker-image: 'condaforge/mambaforge:latest'            , qt5-dir: 'lib/cmake/Qt5'         , wheel-platform-name: ''  },
             {key: 'cpyth-ngui-arm64',  platform: 'linux/arm64' , conda: '0', gui: '0', docker-image: 'nsdf/manylinux2014_aarch64:latest'       , qt5-dir: ''                      , wheel-platform-name: 'manylinux2014_aarch64' },
+            
+            {key: 'conda-ygui-amd64',  platform: 'linux/amd64' , conda: '1', gui: '1', docker-image: 'condaforge/mambaforge:latest'            , qt5-dir: 'lib/cmake/Qt5'         , wheel-platform-name: ''  },
             {key: 'conda-ngui-arm64',  platform: 'linux/arm64' , conda: '1', gui: '0', docker-image: 'condaforge/mambaforge:latest'            , qt5-dir: ''                      , wheel-platform-name: ''  }
           ]
      
@@ -81,38 +63,40 @@ jobs:
             #!/bin/bash
             set -e 
             set -x  
+            
             GIT_TAG=$(git describe --tags --exact-match 2>/dev/null || true)
             PYTHON_VERSION=${{ matrix.python-version }}
-            VISUS_MODVISUS=0
             
             # todo: enable also for arm64
-            if [[ '${{ matrix.python-version }}' == '3.7' && '${{ matrix.specs.gui }}' == '0' && '${{ matrix.specs.platform }}' == 'linux/amd64' ]] ; then
+            VISUS_MODVISUS=0
+            if [[ '${PYTHON_VERSION}' == '3.7' && '${{ matrix.specs.gui }}' == '0' && '${{ matrix.specs.platform }}' == 'linux/amd64' ]] ; then
               VISUS_MODVISUS=1
             fi
 
             mkdir -p build 
             cd build
             cmake \
-            	-DPython_EXECUTABLE=`which python${{ matrix.python-version }}` \
-            	-DQt5_DIR=${{ matrix.specs.qt5-dir }}  \
+            	-DPython_EXECUTABLE=`which python${PYTHON_VERSION}` \
+            	-DQt5_DIR=${{ matrix.specs.qt5-dir }} \
             	-DVISUS_GUI=${{ matrix.specs.gui }}  \
             	-DVISUS_SLAM=${{ matrix.specs.gui }} \
             	-DVISUS_MODVISUS=${VISUS_MODVISUS}  \
             	../
+            	
             make -j
             make install
             
             export PYTHONPATH=$PWD/Release
-            python${{ matrix.python-version }} -m OpenVisus configure || true  # segmentation fault problem
-            python${{ matrix.python-version }} -m OpenVisus test
-            python${{ matrix.python-version }} -m OpenVisus test-gui || true # this can fail because the current OS is too old to support python pyqt (example C++ using qt5.12, python installed 5.12 but python needs GLIB with a version newer than Centos6 that is the OS used for compiling... don't care right now)
+            python${PYTHON_VERSION} -m OpenVisus configure || python${PYTHON_VERSION} -m OpenVisus configure  # segmentation fault problem
+            python${PYTHON_VERSION} -m OpenVisus test
+            python${PYTHON_VERSION} -m OpenVisus test-gui || true # this can fail because the current OS is too old to support python pyqt (example C++ using qt5.12, python installed 5.12 but python needs GLIB with a version newer than Centos6 that is the OS used for compiling... don't care right now)
             unset PYTHONPATH
             
             if [[ "${GIT_TAG}" != "" ]] ; then
               pushd Release/OpenVisus
-              python${{ matrix.python-version }} -m pip install setuptools wheel twine 1>/dev/null 
-              python${{ matrix.python-version }} setup.py -q bdist_wheel --python-tag=cp${PYTHON_VERSION:0:1}${PYTHON_VERSION:2:1} --plat-name=${{ matrix.specs.wheel-platform-name }}
-              python${{ matrix.python-version }} -m twine upload --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }} --skip-existing  "dist/*.whl" 
+              python${PYTHON_VERSION} -m pip install setuptools wheel twine 1>/dev/null 
+              python${PYTHON_VERSION} setup.py -q bdist_wheel --python-tag=cp${PYTHON_VERSION:0:1}${PYTHON_VERSION:2:1} --plat-name=${{ matrix.specs.wheel-platform-name }}
+              python${PYTHON_VERSION} -m twine upload --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }} --skip-existing  "dist/*.whl" 
               popd
               
               if [[ "${VISUS_MODVISUS}" == '1' ]] ; then
@@ -128,7 +112,7 @@ jobs:
             
             EOF
             
-            docker run --rm --platform ${{ matrix.specs.platform }} -v ${{ github.workspace }}:/home/OpenVisus -w /home/OpenVisus ${{ matrix.specs.docker-image }} bash cpython_build.sh
+            docker run --rm --platform ${{ matrix.specs.platform }} -v $PWD:/home/OpenVisus -w /home/OpenVisus ${{ matrix.specs.docker-image }} bash cpython_build.sh
 
       # ////////////////////////////////////////////////////////////
 
@@ -180,8 +164,8 @@ jobs:
              pushd Release/OpenVisus
              cp --no-clobber $CONDA_PREFIX/lib/python${{ matrix.python-version }}/distutils/command/bdist_conda* $CONDA_PREFIX/lib/python${{ matrix.python-version }}/site-packages/setuptools/_distutils/command/ # fix for bdist_not found    
              python setup.py -q bdist_conda 1>/dev/null
-             __filename=`find ${CONDA_PREFIX} -iname "openvisus*.tar.bz2"  | head -n 1`
-             ${HOME}/anaconda3/bin/anaconda --verbose --show-traceback -t ${{ secrets.ANACONDA_TOKEN }} upload "${__filename}"
+             __filename__=`find ${CONDA_PREFIX} -iname "openvisus*.tar.bz2"  | head -n 1`
+             ${HOME}/anaconda3/bin/anaconda --verbose --show-traceback -t ${{ secrets.ANACONDA_TOKEN }} upload "${__filename__}"
              popd
            fi
            
